version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
        - "2181:2181"

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
        - zookeeper
        ports:
        - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    mysql:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: url_shortener
            MYSQL_USER: urlshortener_app
            MYSQL_PASSWORD: password
        ports:
        - "3307:3306"
        volumes:
        - mysql-data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis:alpine
        container_name: redis
        ports:
        - "6379:6379"
        volumes:
        - redis-data:/data

volumes:
    mysql-data:
    redis-data: